apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-gonic-page-deployment
  labels:
    app: gin-gonic-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-gonic-page
  template:
    metadata:
      labels:
        app: gin-gonic-page
    spec:
      containers:
      - name: gin-gonic-page
        image: jgmurua/gin-gonic-page:latest
        ports:
        - containerPort: 3300
        resources:
          limits:
            memory: "8Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gin-gonic-page-service
  labels:
    app: gin-gonic-page
spec:
  type: NodePort
  selector:
    app: gin-gonic-page
  ports:
    - protocol: TCP
      port: 3300
      targetPort: 3300
      nodePort: 30008 #cluster local
