apiVersion: v1
kind: Service
metadata:
  name: {{ include "miapp.fullname" . }}
  labels:
    app: {{ include "miapp.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "miapp.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80