# Minimal settings
global:
  edition: ce
  hosts:
    domain: gitlabathome777.duckdns.org
    https: true
    gitlab:
      https: false
    registry:
      https: false
    minio:
      https: false

prometheus:
  install: false

gitlab-runner:
  install: true
