apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: letschat
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      hostname: mongo
      containers:
      - name: mongo
        image: mongo:3.4.9
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        resources:
          requests:
            memory: "10Mi"
          limits:
            memory: "80Mi"
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
# pvc for persistent storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: letschat
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      
