apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-color-deployment
  labels:
    app: app-color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-color
  template:
    metadata:
      labels:
        app: app-color
    spec:
      containers:
      - name: app-color
        image: jgmurua/app-color:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "8Mi"
        env:
        - name: BACKGROUND_COLOR
          value: "#FF0000"
---
apiVersion: v1
kind: Service
metadata:
  name: app-color-service
  labels:
    app: app-color
spec:
  type: NodePort
  selector:
    app: app-color
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-server-ingress-affinity
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "60"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: app-color-service
            port:
              number: 80
        pathType: Exact