apiVersion: apps/v1
kind: Deployment
metadata:
  name: bailacat-deployment
  labels:
    app: bailacat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bailacat
  template:
    metadata:
      labels:
        app: bailacat
    spec:
      containers:
      - name: bailacat
        image: jgmurua/repojuan
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
