apiVersion: apps/v1
kind: Deployment
metadata:
  name: bailacat-deployment
  labels:
    app: bailacat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bailacat
  template:
    metadata:
      labels:
        app: bailacat
    spec:
      containers:
      - name: bailacat
        image: jgmurua/repojuan
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bailacat-service-nodeport
  labels:
    app: bailacat
spec:
  type: NodePort
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30000
  selector:
    app: bailacat
---
apiVersion: v1
kind: Service
metadata:
  name: bailacat-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    app: bailacat