version: '3'

services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - net2
    volumes:
      - /var/lib/zookeeper/data

  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1  # Ajusta el factor de replicación del tema __consumer_offsets
    networks:
      - net2
    volumes:
      - /var/lib/kafka/data
    depends_on:
      - zookeeper

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    networks:
      - net2
    extra_hosts:
      - "kafka:kafka"

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
    networks:
      - net2
    extra_hosts:
      - "kafka:kafka"

networks:
  net2:
    driver: bridge

