
replicaCount: 1
image:
  repository: jgmurua/repojuanmulti
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
service:
  type: ClusterIP
  port: 8080