name: Deploy Gitlab to Kubernetes

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'version'  

jobs:
  deploy:
    name: Deploy Gitlab to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        #cat ${HOME}/.kube/config
    - name: Deploy Gitlab
      run: |
        kubectl create namespace gitlab --dry-run=client -o yaml | kubectl apply -f -
        helm repo add gitlab http://charts.gitlab.io/



        helm upgrade --install gitlab gitlab/gitlab  \
        --set certmanager-issuer.email="jgmurua@gmail.com" \
        --set global.hosts.domain=gitlabathome777.duckdns.org \
        --set global.hosts.externalIP=127.0.0.1 \
        --set certmanager-issuer.email="jgmurua@gmail.com" \
        --namespace gitlab