name: Deploy Ingress-Controler to Kubernetes

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'version'  

jobs:
  deploy:
    name: Deploy Ingress-Controler to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        #cat ${HOME}/.kube/config
    - name: Deploy Ingress-Controler
      run: |
        NAMESPACE=ingress-basic
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace ingress-basic  --set controller.service.annotations."service\.beta\.kubernetes\.io/azure-load-balancer-health-probe-request-path"=/healthz
      