name: Deploy App into Kubernetes

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'version'  

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
    #- name: Use context
      #run: kubectl config use-context k0s-cluster
    - name: Deploy to K8s
      run: |
          kubectl create namespace monitoreo --dry-run=client -o yaml | kubectl apply -f -
          helm upgrade monitoreo helm/monitoreo -i -n monitoreo
